#spring:
#      datasource:
#      username: root
#      password: boot
#      url: jdbc:mysql://localhost:3306/sbcrudexampledb
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jpa:
#        show-sql: true
#        hibernate:
#          ddl-auto: update
#          dialect: org.hibernate.dialect.MySQL5Dialect
